services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-notification
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-notification_service}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6433:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-notification_service}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

volumes:
  postgres_notification_data:

networks:
  backend:
    driver: bridge
