spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    port: ${mail.port:465}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","logger":"%logger{36}","message":"%msg"}%n'
